name: Kernel Upstreamer
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 17 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Download scripts
        uses: actions/checkout@v2

      - name: add remote
        run: git remote add upstream https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/

      - name: fetch
        env: LINUXVER: ${{ secrets.LINUXVER }}
        run: git fetch upstream $LINUXVER

      - name: fetch head
        run: git merge FETCH_HEAD

      - name: Deploy builder
        env:
          KERNEL_NAME: ${{ secrets.KERNEL_NAME}}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_PUSH_REPO_URL: ${{ secrets.GH_PUSH_REPO_URL }}
        run: ./upstream.sh
